### ISSUE TITLE
Help me please!! Install problem...

### ISSUE THREAD

**Issue by lgcambero** [codepr/creak#1]
![instructor](https://cloud.githubusercontent.com/assets/11602705/21471658/73014e52-ca97-11e6-8fb0-8ccd925502f8.png)

**Comment by codepr** [comment]
Try running the script with `python2 creak.py`, currently module `ConfigParser` works only on python 2.x, I'll patch it to work even with python 3.x.

**Comment by lgcambero** [comment]
Same mistake
![sin titulo](https://cloud.githubusercontent.com/assets/11602705/21482961/a8fb5896-cb59-11e6-9da4-7afca7b01ee5.jpg)

**Comment by codepr** [comment]
Try running `pip install dpkt` or probably better `pip2 install dpkt`
